### ISSUE TITLE
[Solved Alone] Mcrypt_encrypt(); error

### ISSUE THREAD

**Issue by miguel456** [ftbastler/BoNeMEAL#82]
So after meeting all the requirements for Laravel, I extracted the files to the /bans/ directory in my webroot. Then I get an error: "Whoops, looks like something went wrong.". To trace the cause of this error, I go to the app's logs folder, open the most recent one, and here's what I find:

`[2016-08-15 23:15:51] production.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Key of size 26 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported' in [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php:81
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mcrypt_encrypt(...', '[Censored]\bans\app...', 81, Array)
#1 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php(81): mcrypt_encrypt('rijndael-128', 'SomeRandomStrin...', 's:40:"XHR3WBjMx...', 'cbc', '\xB8TB\xE5b\n\x18\x9D\x85\xA1\xD5;\x19\x07\xB2...')
#2 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php(60): Illuminate\Encryption\Encrypter->padAndMcrypt('XHR3WBjMxZNLMjP...', '\xB8TB\xE5b\n\x18\x9D\x85\xA1\xD5;\x19\x07\xB2...')
#3 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(108): Illuminate\Encryption\Encrypter->encrypt('XHR3WBjMxZNLMjP...')
#4 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(40): Illuminate\Cookie\Middleware\EncryptCookies->encrypt(Object(Illuminate\Http\RedirectResponse))
#5 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#7 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#9 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 [Censored]\bans\application\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#12 [Censored]\bans\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#13 {main}  `

It looks like it is something related to mcrypt. But it wasn't mentioned in the requirements for  Laravel...
Here are my specs:
PHP Version: 5.6.51
OpenSSL: Loaded
Mbstring: Loaded
PDO: Loaded
Tokenizer: PHP's website said that Tokenizer didn't need any extensions defined for it to be used, so I left it untouched.
Webserver: IIS 10/Windows (The provided .htaccess with rewrite rules was converted into a web.config, so it should work)
(IIS Also doesn't let anyone list directory contents/or open files within /application.)

Web.config: XML is filtered, link below vv
##  Hastebin paste: [http://hastebin.com/kojufefija.xml](url)

I don't really know what may be causing this. Maybe system limitation? Misconfigured IIS? 
Could somebody help with this?
Thx in advance.
EDIT: After searching other issues, I'm trying to change mcrypt's key size in the settings (came from #29 ) If that doesn't work I'll keep this issue open.

EDIT 2: Searched Issue 29. Looks like I need to change the .env file, or rename it, but I don't know what extension to put!

**Comment by miguel456** [comment]
@ftbastler Please help me, the other issue reports don't seem to have any answers about this :_:

**Comment by miguel456** [comment]
Really? Managed to successfully get redirected to /install after running this command `php artisan key:generate` and pasting it in the renamed .env file. You guys should give us this instruction in case someone has the same problem!
Now I have to deal with url rewrite, which is easy. Issue 29 was what helped me really. By the way, is this repo "dead"? No one has been responding to tickets and I had after much trouble to figure it out without help.
