### ISSUE TITLE
Error on index.php/install

### ISSUE THREAD

**Issue by Robpizza** [ftbastler/BoNeMEAL#83]
I get this error when i visit  $domain/Bans/index.php/install
http://hastebin.com/uzawexeqeg.tex

`[2016-09-21 15:52:16] production.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Key of size 26 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported' in /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:81
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mcrypt_encrypt(...', '/var/www/html/B...', 81, Array)
#1 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(81): mcrypt_encrypt('rijndael-128', 'SomeRandomStrin...', 's:40:"Szh8wEV81...', 'cbc', '\x1D\xB8\x89r\xE7\x03h\x96\xCAPS\x05\xFF\xDB\x90...')
#2 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(60): Illuminate\Encryption\Encrypter->padAndMcrypt('Szh8wEV81yjrAkR...', '\x1D\xB8\x89r\xE7\x03h\x96\xCAPS\x05\xFF\xDB\x90...')
#3 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(108): Illuminate\Encryption\Encrypter->encrypt('Szh8wEV81yjrAkR...')
#4 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Cookie\Middleware\EncryptCookies->encrypt(Object(Illuminate\Http\Response))
#5 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#7 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#9 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#12 /var/www/html/Bans/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#13 {main}

`

**Comment by Robpizza** [comment]
`roduction.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Key of size 26 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported' in /var/www/html/Bans/application/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:81 Stack trace: #0`

**Comment by Robpizza** [comment]
Bump?

**Comment by Robpizza** [comment]
uknow.. ill use another cms. thanks for you help -.-
